version: '3.8'
services:

  workout-service:
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" 

  data-initializer:
    build: 
      context: .
      dockerfile: Dockerfile.insertion
    command: "sh -c 'npx prisma migrate deploy && node dataInsertion.js'"
    depends_on:
      - database     