version: '3.8'
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U wt" ]
      interval: 5s
      timeout: 2s
      retries: 10

  workout-service:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      database:
        condition: service_healthy

  data-initializer:
    build: 
      context: .
      dockerfile: Dockerfile.insertion
    command: "sh -c 'npx prisma migrate deploy && node dataInsertion.js'"
    depends_on:
      database:
        condition: service_healthy